"""init schema

Revision ID: 106f9e1502c7
Revises: 89cfee5e1f9f
Create Date: 2025-09-09 16:15:48.219999

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '106f9e1502c7'
down_revision = '89cfee5e1f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
