"""init schema

Revision ID: bb1b54e8d451
Revises: 
Create Date: 2025-09-04 22:12:54.368714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1b54e8d451'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('service_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('primary_mechanic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_mechanic_id'], ['mechanic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_mechanics',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanic.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_ticket.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'mechanic_id')
    )
    op.create_table('ticket_parts',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['service_ticket.id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'inventory_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_parts')
    op.drop_table('ticket_mechanics')
    op.drop_table('service_ticket')
    op.drop_table('user')
    op.drop_table('mechanic')
    op.drop_table('inventory')
    # ### end Alembic commands ###
